# Generated by Django 5.2.17 on 2026-09-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academy_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/academies/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/managers/'),
        ),
    ]
