# Generated by Django 5.2.17 on 2026-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0005_userprofile_academy_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='academy_certificate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='manager_certificate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
