# Generated by Django 5.2.17 on 2026-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0010_playerregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerRegistration',
        ),
        migrations.AddField(
            model_name='player',
            name='is_evaluated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, choices=[('Right', 'Right'), ('Left', 'Left'), ('Both', 'Both')], max_length=20, null=True),
        ),
    ]
